"""added category column

Revision ID: 1c1bf110b191
Revises: db8399b9051a
Create Date: 2026-03-03 16:39:31.762609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c1bf110b191'
down_revision: Union[str, Sequence[str], None] = 'db8399b9051a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_movements', sa.Column('category', sa.String(length=50), nullable=False))
    op.alter_column('debt_payment', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('debt_transaction', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('purchase_offers', 'purchase_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_offers', 'offer_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchase_offers', 'created_by',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_constraint(op.f('purchase_offers_product_id_fkey'), 'purchase_offers', type_='foreignkey')
    op.drop_constraint(op.f('purchase_offers_purchase_id_fkey'), 'purchase_offers', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_offers', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'purchase_offers', 'purchase', ['purchase_id'], ['id'])
    op.alter_column('reconciliation', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reconciliation', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'purchase_offers', type_='foreignkey')
    op.drop_constraint(None, 'purchase_offers', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_offers_purchase_id_fkey'), 'purchase_offers', 'purchase', ['purchase_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('purchase_offers_product_id_fkey'), 'purchase_offers', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('purchase_offers', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('purchase_offers', 'offer_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchase_offers', 'purchase_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('debt_transaction', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('debt_payment', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('cash_movements', 'category')
    # ### end Alembic commands ###
