"""Add status to Waiter, add due_date to DebtTransaction

Revision ID: 5749df3bef6a
Revises: 
Create Date: 2026-02-09 15:55:21.438611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5749df3bef6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_report', if_exists=True)
    with op.batch_alter_table('debt_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'supplier', ['supplier_id'], ['id'])

    with op.batch_alter_table('waiter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiter', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('debt_transaction', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    op.create_table('reconciliation_report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expected_cash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('actual_cash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('counter_person', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('reconciliation_report_pkey')),
    sa.UniqueConstraint('report_date', name=op.f('reconciliation_report_report_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
