"""improved tables

Revision ID: 8b1ad04533f2
Revises: dcc50b14300a
Create Date: 2026-02-13 15:28:11.796866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1ad04533f2'
down_revision = 'dcc50b14300a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_close_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_close_id', sa.Integer(), nullable=False),
    sa.Column('previous_closing_stock', sa.Integer(), nullable=False),
    sa.Column('new_closing_stock', sa.Integer(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('revenue_delta', sa.Float(), nullable=False),
    sa.Column('profit_delta', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_close_id'], ['daily_close.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debt_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('received_by', sa.String(length=80), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['debt_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('price_delta', sa.Float(), nullable=False),
    sa.Column('cost_delta', sa.Float(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('previous_total_price', sa.Float(), nullable=False),
    sa.Column('previous_total_cost', sa.Float(), nullable=False),
    sa.Column('previous_quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debt_transaction', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('outstanding_debt')
        batch_op.drop_column('is_paid')

    with op.batch_alter_table('debtor', schema=None) as batch_op:
        batch_op.drop_column('total_debt')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('issued_by',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('issued_by',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('debtor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_debt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('debt_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('outstanding_debt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    op.drop_table('sale_adjustments')
    op.drop_table('debt_payment')
    op.drop_table('daily_close_adjustment')
    # ### end Alembic commands ###
